### ISSUE TITLE
PHP errors converteren naar exceptions

### ISSUE THREAD

**Issue by harmenjanssen** [grrr-amsterdam/garp3#27]
Ik heb nog eens zitten denken over dat probleem van vandaag.  
Wat me heel erg stoort is dat hier een notice over gegenereerd werd, maar een notice is hetzelfde als geen error, terwijl het resultaat nogal desastreus was. 

[Dit is een voorbeeld van iemand die errors converteert naar exceptions](http://php.net/manual/en/function.set-error-handler.php#112881)

[Hier een vergelijkbaar voorbeeld van PHP.net zelf, gebruikmakende van de ErrorException class](http://php.net/manual/en/class.errorexception.php)

Moeten wij ook zoiets gaan doen? Ik wil eigenlijk gewoon alles kunnen opvangen, notices en warnings zijn geen doen, omdat ze het programma gewoon doorlaten, terwijl er potentieel, zoals vandaag nogal wat gevolgen aan hangen.

Wat zijn de nadelen? 

1. We moeten letterlijk IEDER brandje dat er is blussen, want gebruikers krijgen een foutmelding te zien. Dus ook iedere `undefined index` die normaal gesproken automatisch goed zou komen breekt nu de user experience en wij moeten aan de bak om een fix te deployen.
2. ?

Kunnen we hierover discussiëren?

**Comment by aapit** [comment]
Ik vind het een heel goed idee. In elk geval op papier.
Het enige grote nadeel lijkt me inderdaad de bewerkelijkheid, die naast verveling van developers ook potentieel hogere kosten oplevert, in elk geval in het begin. Maar ik denk / hoop dat we dat er wel uit zouden kunnen halen op termijn door het voorkomen van dit soort nasty verrassingen.

Wat denk je van:
- een betabranch van Garp maken met dit erin
- het uitproberen op een overzichtelijk project
- het een week of twee laten draaien en goed Sentry monitoren voor dit project

**Comment by harmenjanssen** [comment]
Ja! Makes sense. Laten we het doen.   
Ik zet even een lijntje uit bij project management om hier tijd voor te maken.

**Comment by harmenjanssen** [comment]
@aapit @HammenWS Zie https://github.com/grrr-amsterdam/garp3/pull/30 voor een implementatie.

Wat zou een goed project zijn om dit uit te proberen?

**Comment by aapit** [comment]
Ye? Fastned? Of hebben we een kleiner project nodig?

**Comment by harmenjanssen** [comment]
Nee, lijkt me prima.  
@HammenWS Wil jij in Fastned de Garp dependency naar `dev-feature/error-reporting` wijzen wanneer je deze weer deployed? (zie ook https://packagist.org/packages/grrr-amsterdam/garp3#dev-feature/error-reporting)

**Comment by aapit** [comment]
Markant wat er dan boven komt drijven als je ineens de GitHub app gebruikt 😅
Zullen we deze na vier jaar maar dichtgooien anders, @harmenjanssen ?

**Comment by harmenjanssen** [comment]
Haha, ik denk inderdaad niet dat het er nog van komt. 😄
