### ISSUE TITLE
CDN distribution seems broken in master

### ISSUE THREAD

**Issue by schoenkaft** [grrr-amsterdam/garp3#69]
When running `g cdn distribute --to=<stage>`, nothing seems to happen. Also trying to tab-complete the command `g cdn dist...` locks up the terminal.

**Comment by schoenkaft** [comment]
Tested in both `bash` and `fish` by the way.

**Comment by harmenjanssen** [comment]
I'm afraid tab-completion depends on your shell, there's nothing in Garp to
help with that.

I mean there was a `complete` command for this purpose but it's no longer
maintained.


On Dec 22, 2017 09:16, "Koen" <notifications@github.com> wrote:

Tested in both bash and fish by the way.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/grrr-amsterdam/garp3/issues/69#issuecomment-353546582>,
or mute the thread

**Comment by schoenkaft** [comment]
I have tab completion for `g`:

```
# g <command> <action> <args>
_g() {
        local cur prev opts base cmdlist
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"

        if [ $prev != 'g' ]; then
                # If a command is chosen, try to complete its methods
                cmdlist=$(g $prev complete $cur)
        else
                # Ask Golem for the available commands
                cmdlist=$(g complete $COMP_LINE)
        fi
        COMPREPLY=( $(compgen -W "${cmdlist}" ${cur}) )

        return 0
}
complete -o default -F _g g
```

When using `v3.11.18` it works fine, when switching to `master`, it doesn't. It locks up everything until I send a `SIGINT`. But that's not the problem of course. The problem is that `g cdn distribute` doesn't do anything

**Comment by harmenjanssen** [comment]
Aha!

But yes, you're right of course.
But that's the problem with Garp in general: it needs a host project to
test a lot of stuff.
`g cdn distribute` lacks all the configuration needed to function when run
in isolation.
The same is true for anything using a database for instance.

**Comment by schoenkaft** [comment]
@harmenjanssen I used both Melkweg and Entree to test of course... The problem lies here:

https://github.com/grrr-amsterdam/garp3/commit/9254f9c812c384da6f870e6f8dce5f4d6fef6d0d

If I comment out the changes made in `scripts/garp3.php` everything works fine.

**Comment by harmenjanssen** [comment]
Ah! Yes! That's interesting. 
The same problem was reporting by Kevin. It's got something to do with OSX High Sierra, we think. 
I haven't had time to investigate proper (and also am not on High Sierra myself).

But there's something wrong with reading `STDIN` on that version somehow. 

(so now I'm really hoping you are also on High Sierra otherwise the whole idea falls through)

**Comment by schoenkaft** [comment]
Sierra, sorry 👎

**Comment by harmenjanssen** [comment]
Goshdarnit.

It might be PHP 7.1 then? I'm still on 7.0...

**Comment by schoenkaft** [comment]
Installing `php70 --with-httpd` now. Also `php72` starts to give deprecation warnings, but let's focus on this one first.

**Comment by harmenjanssen** [comment]
It might also be a change in the way that constant is used, either from new PHP configuration or from the way PHP is compiled.

See also: http://docs.php.net/manual/da/features.commandline.io-streams.php
`STDIN` is nothing more than a constant pointing to an already opened stream. Might be it's not open in your case. 

You could try using `$stdin = fopen('php://stdin', 'r');` manually.

**Comment by schoenkaft** [comment]
All version of `php7x` are not working. 

> You could try using $stdin = fopen('php://stdin', 'r'); manually.

Like replace `$stdin = trim(stream_get_contents(STDIN));` with that?

```php
Fatal error: Uncaught Exception: Data passed thru STDIN needs to be in JSON-format in /Users/koen/Sites/garp3/library/Garp/Cli/Command/Cdn.php:152
Stack trace:
#0 /Users/koen/Sites/garp3/library/Garp/Cli/Command/Cdn.php(118): Garp_Cli_Command_Cdn->_parseStdin(Resource id #209)
#1 /Users/koen/Sites/garp3/library/Garp/Cli/Command/Cdn.php(38): Garp_Cli_Command_Cdn->_gatherConfigVars()
#2 /Users/koen/Sites/garp3/library/Garp/Cli/Command.php(68): Garp_Cli_Command_Cdn->distribute(Array)
#3 /Users/koen/Sites/garp3/scripts/garp.php(178): Garp_Cli_Command->main(Array)
#4 /Users/koen/Sites/garp3/scripts/g(3): require_once('/Users/koen/Sit...')
#5 {main}
  thrown in /Users/koen/Sites/garp3/library/Garp/Cli/Command/Cdn.php on line 152
```

**Comment by harmenjanssen** [comment]
Aha! But we're getting somewhere.
Right now the problem seems to be that data is coming into the command class (via the constructor), but I'm assuming in this case you're not piping anything into it? 
Are you using `trim` before passing the data into the command?

**Comment by harmenjanssen** [comment]
Or check with `var_dump()` what `$stdin` actually contains.

**Comment by harmenjanssen** [comment]
Oh of course, `$stdin` is just the resource. 

The JSON error pops up because the command class gets a truthy value as stdin, in your case the pointer. 
You should use `fread` to get at the contents, something like this:

```php
$handle = fopen('php://stdin', 'r');
$stdin = trim(fread($handle, filesize($filename)));
fclose($handle);
```

It might be we just recreated the original bug, because this basically replicates `stream_get_contents(STDIN)`.

**Comment by harmenjanssen** [comment]
I take it, by the way, that this problem is not limited to `cdn distribute`? 
The same problem pops up when using `g cache clear` for example? (not the "STDIN should be JSON one, but the previous one where nothing happens)

**Comment by schoenkaft** [comment]
Getting somewhere. If I run `test | g cdn distribute --to=development` everything works fine, and distribution starts.

So this is what I have in my code:
```php
$stdin = trim(stream_get_contents(STDIN));
var_dump($stdin);
```

I run:
```
test | g cdn distribute --to=development
```

Output:
```
test | g cdn distribute --to=development
string(0) ""
Distributing 106 assets since 8-12-2017
```

Running the command without anything piped in front of it locks up the command and nothing happens.

**Comment by schoenkaft** [comment]
> I take it, by the way, that this problem is not limited to cdn distribute?
The same problem pops up when using g cache clear for example? (not the "STDIN should be JSON one, but the previous one where nothing happens)

Yeah. That's why tab completion wasn't working either.

**Comment by harmenjanssen** [comment]
I seem to have the same problem. How did I not notice this before? 💩 

Anyways. I found something: 

```php
stream_set_blocking(STDIN, false);
$stdin = trim(stream_get_contents(STDIN));
```

This seems to solve the problem in my case!

**Comment by harmenjanssen** [comment]
❤️ Vacation time!

**Comment by schoenkaft** [comment]
Bug free-2018, here we come 💯
