### ISSUE TITLE
CKEditor te breed

### ISSUE THREAD

**Issue by harmenjanssen** [grrr-amsterdam/garp3#94]
Ik was dat eens aan het debuggen en ik snap er niet zoveel van. 
Die containers (van de input fields) zijn allemaal standaard te breed en worden uit beeld geduwd door `padding-left`.
Echter, de reguliere invoervelden krijgen allemaal een gecorrigeerde breedte hard in een style attribuut. Dit is Ext's runtime responsive layout natuurlijk, maar ik zou dat behavior ook graag op onze CKEditor hebben, het staat zo slordig.

Heb jij misschien een snel idee, @PieturP ?

**Comment by PieturP** [comment]
Geen snel idee, maar misschien kan ik er binnenkort even een half uurtje / drie kwartier naar kijken?

Peter | eenengelswoord.nl
06 1945 9741

**Comment by harmenjanssen** [comment]
Ja, dat zou wel aardig zijn 🙂 
Thanks!

**Comment by martijngastkemper** [comment]
Solved #151

**Comment by harmenjanssen** [comment]
Wow, ik was dit issue helemaal vergeten. 🙂 
Thanks, @PieturP!
